# Generated by Django 4.2.2 on 2023-07-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Email', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('Password', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
